// Core 500 Japanese Words — Frequency-optimized for conversation learners
// Sources: JLPT N5/N4 corpus, Core 2k frequency list, CEJC spoken conversation corpus
// N5: words 1-300 (highest frequency beginner words)
// N4: words 301-500 (highest frequency intermediate words for daily conversation)

export type JlptLevel = "N5" | "N4";

export interface CoreWord {
  word: string;       // Japanese word (kanji where standard)
  reading: string;    // hiragana reading
  romaji: string;     // romanization
  meaning: string;    // English meaning (concise)
  example: string;    // natural example sentence in Japanese
  exampleEn: string;  // English translation of example
  level: JlptLevel;
}

export const CORE_500: CoreWord[] = [
  // ── N5 Core (1–300) ──

  // Pronouns & People
  { word: "私", reading: "わたし", romaji: "watashi", meaning: "I / me", example: "私は学生です。", exampleEn: "I am a student.", level: "N5" },
  { word: "あなた", reading: "あなた", romaji: "anata", meaning: "you", example: "あなたの名前は何ですか？", exampleEn: "What is your name?", level: "N5" },
  { word: "彼", reading: "かれ", romaji: "kare", meaning: "he / him", example: "彼は学校に行きます。", exampleEn: "He goes to school.", level: "N5" },
  { word: "彼女", reading: "かのじょ", romaji: "kanojo", meaning: "she / her", example: "彼女は先生です。", exampleEn: "She is a teacher.", level: "N5" },
  { word: "私たち", reading: "わたしたち", romaji: "watashitachi", meaning: "we / us", example: "私たちは友達です。", exampleEn: "We are friends.", level: "N5" },
  { word: "彼ら", reading: "かれら", romaji: "karera", meaning: "they / them", example: "彼らは元気です。", exampleEn: "They are fine.", level: "N5" },

  // Question Words
  { word: "何", reading: "なに", romaji: "nani", meaning: "what", example: "これは何ですか？", exampleEn: "What is this?", level: "N5" },
  { word: "誰", reading: "だれ", romaji: "dare", meaning: "who", example: "あの人は誰ですか？", exampleEn: "Who is that person?", level: "N5" },
  { word: "どこ", reading: "どこ", romaji: "doko", meaning: "where", example: "トイレはどこですか？", exampleEn: "Where is the bathroom?", level: "N5" },
  { word: "いつ", reading: "いつ", romaji: "itsu", meaning: "when", example: "いつ来ますか？", exampleEn: "When are you coming?", level: "N5" },
  { word: "なぜ", reading: "なぜ", romaji: "naze", meaning: "why", example: "なぜ泣いていますか？", exampleEn: "Why are you crying?", level: "N5" },
  { word: "どう", reading: "どう", romaji: "dō", meaning: "how", example: "気分はどうですか？", exampleEn: "How are you feeling?", level: "N5" },
  { word: "どの", reading: "どの", romaji: "dono", meaning: "which", example: "どのかばんですか？", exampleEn: "Which bag is it?", level: "N5" },
  { word: "どれ", reading: "どれ", romaji: "dore", meaning: "which one", example: "どれがいいですか？", exampleEn: "Which one is good?", level: "N5" },
  { word: "どちら", reading: "どちら", romaji: "dochira", meaning: "which / which way", example: "どちらが好きですか？", exampleEn: "Which do you like?", level: "N5" },
  { word: "いくら", reading: "いくら", romaji: "ikura", meaning: "how much", example: "これはいくらですか？", exampleEn: "How much is this?", level: "N5" },
  { word: "いくつ", reading: "いくつ", romaji: "ikutsu", meaning: "how many", example: "りんごはいくつありますか？", exampleEn: "How many apples are there?", level: "N5" },

  // Numbers
  { word: "一", reading: "いち", romaji: "ichi", meaning: "one", example: "一つください。", exampleEn: "Please give me one.", level: "N5" },
  { word: "二", reading: "に", romaji: "ni", meaning: "two", example: "二人います。", exampleEn: "There are two people.", level: "N5" },
  { word: "三", reading: "さん", romaji: "san", meaning: "three", example: "三つ買いました。", exampleEn: "I bought three.", level: "N5" },
  { word: "四", reading: "し／よん", romaji: "shi / yon", meaning: "four", example: "四時に会いましょう。", exampleEn: "Let's meet at four o'clock.", level: "N5" },
  { word: "五", reading: "ご", romaji: "go", meaning: "five", example: "五分待ってください。", exampleEn: "Please wait five minutes.", level: "N5" },
  { word: "六", reading: "ろく", romaji: "roku", meaning: "six", example: "六時に起きます。", exampleEn: "I wake up at six.", level: "N5" },
  { word: "七", reading: "なな／しち", romaji: "nana / shichi", meaning: "seven", example: "七日間旅行します。", exampleEn: "I travel for seven days.", level: "N5" },
  { word: "八", reading: "はち", romaji: "hachi", meaning: "eight", example: "八時に寝ます。", exampleEn: "I go to sleep at eight.", level: "N5" },
  { word: "九", reading: "きゅう／く", romaji: "kyū / ku", meaning: "nine", example: "九月が好きです。", exampleEn: "I like September.", level: "N5" },
  { word: "十", reading: "じゅう", romaji: "jū", meaning: "ten", example: "十人の友達がいます。", exampleEn: "I have ten friends.", level: "N5" },
  { word: "百", reading: "ひゃく", romaji: "hyaku", meaning: "hundred", example: "百円です。", exampleEn: "It is one hundred yen.", level: "N5" },
  { word: "千", reading: "せん", romaji: "sen", meaning: "thousand", example: "千円あります。", exampleEn: "I have one thousand yen.", level: "N5" },
  { word: "万", reading: "まん", romaji: "man", meaning: "ten thousand", example: "一万円払いました。", exampleEn: "I paid ten thousand yen.", level: "N5" },
  { word: "零", reading: "ぜろ／れい", romaji: "zero / rei", meaning: "zero", example: "点数はゼロです。", exampleEn: "The score is zero.", level: "N5" },

  // Time Words
  { word: "今", reading: "いま", romaji: "ima", meaning: "now", example: "今、何時ですか？", exampleEn: "What time is it now?", level: "N5" },
  { word: "今日", reading: "きょう", romaji: "kyō", meaning: "today", example: "今日は暑いですね。", exampleEn: "It is hot today, isn't it?", level: "N5" },
  { word: "明日", reading: "あした", romaji: "ashita", meaning: "tomorrow", example: "明日また来ます。", exampleEn: "I will come again tomorrow.", level: "N5" },
  { word: "昨日", reading: "きのう", romaji: "kinō", meaning: "yesterday", example: "昨日映画を見ました。", exampleEn: "I watched a movie yesterday.", level: "N5" },
  { word: "朝", reading: "あさ", romaji: "asa", meaning: "morning", example: "朝ご飯を食べます。", exampleEn: "I eat breakfast in the morning.", level: "N5" },
  { word: "昼", reading: "ひる", romaji: "hiru", meaning: "noon / daytime", example: "昼ご飯はどこで食べますか？", exampleEn: "Where do you eat lunch?", level: "N5" },
  { word: "夜", reading: "よる", romaji: "yoru", meaning: "evening / night", example: "夜は静かです。", exampleEn: "It is quiet at night.", level: "N5" },
  { word: "今週", reading: "こんしゅう", romaji: "konshū", meaning: "this week", example: "今週は忙しいです。", exampleEn: "I am busy this week.", level: "N5" },
  { word: "来週", reading: "らいしゅう", romaji: "raishū", meaning: "next week", example: "来週また話しましょう。", exampleEn: "Let's talk again next week.", level: "N5" },
  { word: "先週", reading: "せんしゅう", romaji: "senshū", meaning: "last week", example: "先週旅行しました。", exampleEn: "I traveled last week.", level: "N5" },
  { word: "今年", reading: "ことし", romaji: "kotoshi", meaning: "this year", example: "今年の目標は何ですか？", exampleEn: "What is your goal this year?", level: "N5" },
  { word: "来年", reading: "らいねん", romaji: "rainen", meaning: "next year", example: "来年日本に行きます。", exampleEn: "I am going to Japan next year.", level: "N5" },
  { word: "去年", reading: "きょねん", romaji: "kyonen", meaning: "last year", example: "去年から日本語を勉強しています。", exampleEn: "I have been studying Japanese since last year.", level: "N5" },
  { word: "時間", reading: "じかん", romaji: "jikan", meaning: "time / hours", example: "時間がありません。", exampleEn: "I don't have time.", level: "N5" },
  { word: "分", reading: "ふん／ぷん", romaji: "fun / pun", meaning: "minute", example: "五分待ってください。", exampleEn: "Please wait five minutes.", level: "N5" },
  { word: "時", reading: "じ", romaji: "ji", meaning: "o'clock / hour", example: "三時に会いましょう。", exampleEn: "Let's meet at three o'clock.", level: "N5" },

  // Days of the Week
  { word: "月曜日", reading: "げつようび", romaji: "getsuyōbi", meaning: "Monday", example: "月曜日は学校があります。", exampleEn: "There is school on Monday.", level: "N5" },
  { word: "火曜日", reading: "かようび", romaji: "kayōbi", meaning: "Tuesday", example: "火曜日に会議があります。", exampleEn: "There is a meeting on Tuesday.", level: "N5" },
  { word: "水曜日", reading: "すいようび", romaji: "suiyōbi", meaning: "Wednesday", example: "水曜日に映画を見ます。", exampleEn: "I watch a movie on Wednesday.", level: "N5" },
  { word: "木曜日", reading: "もくようび", romaji: "mokuyōbi", meaning: "Thursday", example: "木曜日に友達と会います。", exampleEn: "I meet a friend on Thursday.", level: "N5" },
  { word: "金曜日", reading: "きんようび", romaji: "kin'yōbi", meaning: "Friday", example: "金曜日は楽しいです。", exampleEn: "Friday is fun.", level: "N5" },
  { word: "土曜日", reading: "どようび", romaji: "doyōbi", meaning: "Saturday", example: "土曜日に買い物します。", exampleEn: "I go shopping on Saturday.", level: "N5" },
  { word: "日曜日", reading: "にちようび", romaji: "nichiyōbi", meaning: "Sunday", example: "日曜日に家にいます。", exampleEn: "I am at home on Sunday.", level: "N5" },

  // Greetings & Expressions
  { word: "はい", reading: "はい", romaji: "hai", meaning: "yes", example: "はい、わかりました。", exampleEn: "Yes, I understand.", level: "N5" },
  { word: "いいえ", reading: "いいえ", romaji: "iie", meaning: "no", example: "いいえ、違います。", exampleEn: "No, that is wrong.", level: "N5" },
  { word: "すみません", reading: "すみません", romaji: "sumimasen", meaning: "excuse me / sorry", example: "すみません、ちょっといいですか？", exampleEn: "Excuse me, do you have a moment?", level: "N5" },
  { word: "ありがとう", reading: "ありがとう", romaji: "arigatō", meaning: "thank you", example: "ありがとうございます。", exampleEn: "Thank you very much.", level: "N5" },
  { word: "ごめんなさい", reading: "ごめんなさい", romaji: "gomen nasai", meaning: "I'm sorry", example: "ごめんなさい、遅れました。", exampleEn: "I'm sorry, I was late.", level: "N5" },
  { word: "おはよう", reading: "おはよう", romaji: "ohayō", meaning: "good morning", example: "おはようございます。", exampleEn: "Good morning.", level: "N5" },
  { word: "こんにちは", reading: "こんにちは", romaji: "konnichiwa", meaning: "hello / good afternoon", example: "こんにちは、元気ですか？", exampleEn: "Hello, how are you?", level: "N5" },
  { word: "こんばんは", reading: "こんばんは", romaji: "konbanwa", meaning: "good evening", example: "こんばんは、今日はどうでしたか？", exampleEn: "Good evening, how was today?", level: "N5" },
  { word: "さようなら", reading: "さようなら", romaji: "sayōnara", meaning: "goodbye", example: "さようなら、またね。", exampleEn: "Goodbye, see you later.", level: "N5" },
  { word: "よろしく", reading: "よろしく", romaji: "yoroshiku", meaning: "nice to meet you / please", example: "よろしくお願いします。", exampleEn: "Nice to meet you.", level: "N5" },
  { word: "どうも", reading: "どうも", romaji: "dōmo", meaning: "thanks / hello (casual)", example: "どうもありがとうございます。", exampleEn: "Thank you very much.", level: "N5" },
  { word: "いただきます", reading: "いただきます", romaji: "itadakimasu", meaning: "let's eat (before meal)", example: "ご飯の前にいただきますと言います。", exampleEn: "We say 'itadakimasu' before a meal.", level: "N5" },
  { word: "ごちそうさま", reading: "ごちそうさま", romaji: "gochisōsama", meaning: "thank you for the meal", example: "食べた後でごちそうさまと言います。", exampleEn: "We say 'gochisōsama' after eating.", level: "N5" },

  // Essential Verbs — Being & Existence
  { word: "います", reading: "います", romaji: "imasu", meaning: "to be / exist (animate)", example: "猫が部屋にいます。", exampleEn: "There is a cat in the room.", level: "N5" },
  { word: "あります", reading: "あります", romaji: "arimasu", meaning: "to be / exist (inanimate)", example: "机の上に本があります。", exampleEn: "There is a book on the desk.", level: "N5" },
  { word: "です", reading: "です", romaji: "desu", meaning: "to be (copula)", example: "これは本です。", exampleEn: "This is a book.", level: "N5" },

  // Essential Verbs — Motion
  { word: "行く", reading: "いく", romaji: "iku", meaning: "to go", example: "学校に行きます。", exampleEn: "I go to school.", level: "N5" },
  { word: "来る", reading: "くる", romaji: "kuru", meaning: "to come", example: "友達が家に来ます。", exampleEn: "A friend is coming to my house.", level: "N5" },
  { word: "帰る", reading: "かえる", romaji: "kaeru", meaning: "to return / go home", example: "六時に家に帰ります。", exampleEn: "I return home at six.", level: "N5" },
  { word: "出る", reading: "でる", romaji: "deru", meaning: "to go out / leave", example: "八時に家を出ます。", exampleEn: "I leave the house at eight.", level: "N5" },
  { word: "入る", reading: "はいる", romaji: "hairu", meaning: "to enter", example: "部屋に入ります。", exampleEn: "I enter the room.", level: "N5" },
  { word: "乗る", reading: "のる", romaji: "noru", meaning: "to ride / board", example: "電車に乗ります。", exampleEn: "I ride the train.", level: "N5" },
  { word: "降りる", reading: "おりる", romaji: "oriru", meaning: "to get off / descend", example: "次の駅で降ります。", exampleEn: "I get off at the next station.", level: "N5" },
  { word: "歩く", reading: "あるく", romaji: "aruku", meaning: "to walk", example: "公園を歩きます。", exampleEn: "I walk in the park.", level: "N5" },
  { word: "走る", reading: "はしる", romaji: "hashiru", meaning: "to run", example: "毎朝走ります。", exampleEn: "I run every morning.", level: "N5" },

  // Essential Verbs — Daily Actions
  { word: "食べる", reading: "たべる", romaji: "taberu", meaning: "to eat", example: "朝ご飯を食べます。", exampleEn: "I eat breakfast.", level: "N5" },
  { word: "飲む", reading: "のむ", romaji: "nomu", meaning: "to drink", example: "水を飲みます。", exampleEn: "I drink water.", level: "N5" },
  { word: "見る", reading: "みる", romaji: "miru", meaning: "to see / watch", example: "テレビを見ます。", exampleEn: "I watch TV.", level: "N5" },
  { word: "聞く", reading: "きく", romaji: "kiku", meaning: "to listen / ask", example: "音楽を聞きます。", exampleEn: "I listen to music.", level: "N5" },
  { word: "話す", reading: "はなす", romaji: "hanasu", meaning: "to speak / talk", example: "日本語で話します。", exampleEn: "I speak in Japanese.", level: "N5" },
  { word: "読む", reading: "よむ", romaji: "yomu", meaning: "to read", example: "本を読みます。", exampleEn: "I read a book.", level: "N5" },
  { word: "書く", reading: "かく", romaji: "kaku", meaning: "to write", example: "手紙を書きます。", exampleEn: "I write a letter.", level: "N5" },
  { word: "買う", reading: "かう", romaji: "kau", meaning: "to buy", example: "野菜を買います。", exampleEn: "I buy vegetables.", level: "N5" },
  { word: "売る", reading: "うる", romaji: "uru", meaning: "to sell", example: "この店で本を売ります。", exampleEn: "This shop sells books.", level: "N5" },
  { word: "使う", reading: "つかう", romaji: "tsukau", meaning: "to use", example: "毎日スマホを使います。", exampleEn: "I use my smartphone every day.", level: "N5" },
  { word: "作る", reading: "つくる", romaji: "tsukuru", meaning: "to make / create", example: "夕ご飯を作ります。", exampleEn: "I make dinner.", level: "N5" },
  { word: "起きる", reading: "おきる", romaji: "okiru", meaning: "to wake up / get up", example: "七時に起きます。", exampleEn: "I wake up at seven.", level: "N5" },
  { word: "寝る", reading: "ねる", romaji: "neru", meaning: "to sleep / go to bed", example: "十一時に寝ます。", exampleEn: "I go to bed at eleven.", level: "N5" },
  { word: "待つ", reading: "まつ", romaji: "matsu", meaning: "to wait", example: "ここで待ってください。", exampleEn: "Please wait here.", level: "N5" },
  { word: "会う", reading: "あう", romaji: "au", meaning: "to meet", example: "友達に会います。", exampleEn: "I meet a friend.", level: "N5" },
  { word: "知る", reading: "しる", romaji: "shiru", meaning: "to know / find out", example: "その話を知っています。", exampleEn: "I know that story.", level: "N5" },
  { word: "分かる", reading: "わかる", romaji: "wakaru", meaning: "to understand", example: "日本語が分かります。", exampleEn: "I understand Japanese.", level: "N5" },
  { word: "思う", reading: "おもう", romaji: "omou", meaning: "to think / feel", example: "それはいいと思います。", exampleEn: "I think that is good.", level: "N5" },
  { word: "言う", reading: "いう", romaji: "iu", meaning: "to say / tell", example: "何と言いましたか？", exampleEn: "What did you say?", level: "N5" },
  { word: "する", reading: "する", romaji: "suru", meaning: "to do", example: "宿題をします。", exampleEn: "I do homework.", level: "N5" },
  { word: "なる", reading: "なる", romaji: "naru", meaning: "to become", example: "先生になりたいです。", exampleEn: "I want to become a teacher.", level: "N5" },
  { word: "できる", reading: "できる", romaji: "dekiru", meaning: "can do / be able to", example: "日本語が少しできます。", exampleEn: "I can speak a little Japanese.", level: "N5" },
  { word: "もらう", reading: "もらう", romaji: "morau", meaning: "to receive", example: "プレゼントをもらいました。", exampleEn: "I received a present.", level: "N5" },
  { word: "あげる", reading: "あげる", romaji: "ageru", meaning: "to give (to someone)", example: "友達にケーキをあげました。", exampleEn: "I gave cake to my friend.", level: "N5" },
  { word: "くれる", reading: "くれる", romaji: "kureru", meaning: "to give (to me)", example: "母が本をくれました。", exampleEn: "My mother gave me a book.", level: "N5" },

  // Key Adjectives — i-adjectives
  { word: "いい", reading: "いい", romaji: "ii", meaning: "good / fine", example: "今日は天気がいいです。", exampleEn: "The weather is good today.", level: "N5" },
  { word: "悪い", reading: "わるい", romaji: "warui", meaning: "bad", example: "気分が悪いです。", exampleEn: "I feel bad.", level: "N5" },
  { word: "大きい", reading: "おおきい", romaji: "ōkii", meaning: "big / large", example: "大きい犬がいます。", exampleEn: "There is a big dog.", level: "N5" },
  { word: "小さい", reading: "ちいさい", romaji: "chīsai", meaning: "small / little", example: "小さい子供がいます。", exampleEn: "There is a small child.", level: "N5" },
  { word: "新しい", reading: "あたらしい", romaji: "atarashii", meaning: "new", example: "新しいスマホを買いました。", exampleEn: "I bought a new smartphone.", level: "N5" },
  { word: "古い", reading: "ふるい", romaji: "furui", meaning: "old (things)", example: "古い本を読みます。", exampleEn: "I read an old book.", level: "N5" },
  { word: "高い", reading: "たかい", romaji: "takai", meaning: "expensive / tall", example: "あのレストランは高いです。", exampleEn: "That restaurant is expensive.", level: "N5" },
  { word: "安い", reading: "やすい", romaji: "yasui", meaning: "cheap / inexpensive", example: "このお店は安いです。", exampleEn: "This shop is cheap.", level: "N5" },
  { word: "長い", reading: "ながい", romaji: "nagai", meaning: "long", example: "この道は長いです。", exampleEn: "This road is long.", level: "N5" },
  { word: "短い", reading: "みじかい", romaji: "mijikai", meaning: "short", example: "その映画は短いです。", exampleEn: "That movie is short.", level: "N5" },
  { word: "多い", reading: "おおい", romaji: "ōi", meaning: "many / much", example: "人が多いです。", exampleEn: "There are many people.", level: "N5" },
  { word: "少ない", reading: "すくない", romaji: "sukunai", meaning: "few / little", example: "時間が少ないです。", exampleEn: "There is little time.", level: "N5" },
  { word: "暑い", reading: "あつい", romaji: "atsui", meaning: "hot (weather)", example: "今日は暑いですね。", exampleEn: "It's hot today, isn't it.", level: "N5" },
  { word: "寒い", reading: "さむい", romaji: "samui", meaning: "cold (weather)", example: "冬はとても寒いです。", exampleEn: "Winter is very cold.", level: "N5" },
  { word: "熱い", reading: "あつい", romaji: "atsui", meaning: "hot (to the touch)", example: "このお茶は熱いです。", exampleEn: "This tea is hot.", level: "N5" },
  { word: "冷たい", reading: "つめたい", romaji: "tsumetai", meaning: "cold (to the touch)", example: "冷たい水が飲みたいです。", exampleEn: "I want to drink cold water.", level: "N5" },
  { word: "難しい", reading: "むずかしい", romaji: "muzukashii", meaning: "difficult", example: "この問題は難しいです。", exampleEn: "This problem is difficult.", level: "N5" },
  { word: "楽しい", reading: "たのしい", romaji: "tanoshii", meaning: "fun / enjoyable", example: "旅行は楽しいです。", exampleEn: "Travel is fun.", level: "N5" },
  { word: "面白い", reading: "おもしろい", romaji: "omoshiroi", meaning: "interesting / funny", example: "この本は面白いです。", exampleEn: "This book is interesting.", level: "N5" },
  { word: "忙しい", reading: "いそがしい", romaji: "isogashii", meaning: "busy", example: "今日はとても忙しいです。", exampleEn: "I am very busy today.", level: "N5" },
  { word: "早い", reading: "はやい", romaji: "hayai", meaning: "early / fast", example: "今朝は早く起きました。", exampleEn: "I woke up early this morning.", level: "N5" },
  { word: "遅い", reading: "おそい", romaji: "osoi", meaning: "late / slow", example: "今日は電車が遅いです。", exampleEn: "The train is slow today.", level: "N5" },
  { word: "強い", reading: "つよい", romaji: "tsuyoi", meaning: "strong", example: "彼はとても強いです。", exampleEn: "He is very strong.", level: "N5" },
  { word: "弱い", reading: "よわい", romaji: "yowai", meaning: "weak", example: "私は運動が弱いです。", exampleEn: "I am weak at sports.", level: "N5" },
  { word: "白い", reading: "しろい", romaji: "shiroi", meaning: "white", example: "白いシャツを着ています。", exampleEn: "I am wearing a white shirt.", level: "N5" },
  { word: "黒い", reading: "くろい", romaji: "kuroi", meaning: "black", example: "黒い猫がいます。", exampleEn: "There is a black cat.", level: "N5" },
  { word: "赤い", reading: "あかい", romaji: "akai", meaning: "red", example: "赤いりんごを食べました。", exampleEn: "I ate a red apple.", level: "N5" },
  { word: "青い", reading: "あおい", romaji: "aoi", meaning: "blue", example: "空が青いです。", exampleEn: "The sky is blue.", level: "N5" },
  { word: "丸い", reading: "まるい", romaji: "marui", meaning: "round", example: "地球は丸いです。", exampleEn: "The Earth is round.", level: "N5" },

  // Key Adjectives — na-adjectives
  { word: "簡単", reading: "かんたん", romaji: "kantan", meaning: "easy / simple", example: "この料理は簡単です。", exampleEn: "This dish is easy to make.", level: "N5" },
  { word: "きれい", reading: "きれい", romaji: "kirei", meaning: "beautiful / clean", example: "花がきれいです。", exampleEn: "The flowers are beautiful.", level: "N5" },
  { word: "好き", reading: "すき", romaji: "suki", meaning: "liked / favorite", example: "音楽が好きです。", exampleEn: "I like music.", level: "N5" },
  { word: "嫌い", reading: "きらい", romaji: "kirai", meaning: "disliked", example: "虫が嫌いです。", exampleEn: "I dislike insects.", level: "N5" },
  { word: "上手", reading: "じょうず", romaji: "jōzu", meaning: "skillful / good at", example: "彼女は料理が上手です。", exampleEn: "She is good at cooking.", level: "N5" },
  { word: "下手", reading: "へた", romaji: "heta", meaning: "unskillful / poor at", example: "私は歌が下手です。", exampleEn: "I am poor at singing.", level: "N5" },
  { word: "有名", reading: "ゆうめい", romaji: "yūmei", meaning: "famous", example: "あの映画は有名です。", exampleEn: "That movie is famous.", level: "N5" },
  { word: "大切", reading: "たいせつ", romaji: "taisetsu", meaning: "important / precious", example: "家族は大切です。", exampleEn: "Family is important.", level: "N5" },
  { word: "大丈夫", reading: "だいじょうぶ", romaji: "daijōbu", meaning: "okay / all right", example: "大丈夫ですか？", exampleEn: "Are you okay?", level: "N5" },
  { word: "暇", reading: "ひま", romaji: "hima", meaning: "free / not busy", example: "今日は暇ですか？", exampleEn: "Are you free today?", level: "N5" },
  { word: "静か", reading: "しずか", romaji: "shizuka", meaning: "quiet", example: "この図書館は静かです。", exampleEn: "This library is quiet.", level: "N5" },
  { word: "にぎやか", reading: "にぎやか", romaji: "nigiyaka", meaning: "lively / bustling", example: "この町はにぎやかです。", exampleEn: "This town is lively.", level: "N5" },
  { word: "親切", reading: "しんせつ", romaji: "shinsetsu", meaning: "kind / helpful", example: "彼はとても親切です。", exampleEn: "He is very kind.", level: "N5" },
  { word: "元気", reading: "げんき", romaji: "genki", meaning: "healthy / energetic", example: "毎日元気です。", exampleEn: "I am energetic every day.", level: "N5" },

  // Core Nouns — People & Family
  { word: "人", reading: "ひと", romaji: "hito", meaning: "person / people", example: "あの人は誰ですか？", exampleEn: "Who is that person?", level: "N5" },
  { word: "子供", reading: "こども", romaji: "kodomo", meaning: "child", example: "子供が公園で遊んでいます。", exampleEn: "Children are playing in the park.", level: "N5" },
  { word: "男", reading: "おとこ", romaji: "otoko", meaning: "man / male", example: "あの男の人は先生です。", exampleEn: "That man is a teacher.", level: "N5" },
  { word: "女", reading: "おんな", romaji: "onna", meaning: "woman / female", example: "あの女の人は医者です。", exampleEn: "That woman is a doctor.", level: "N5" },
  { word: "友達", reading: "ともだち", romaji: "tomodachi", meaning: "friend", example: "友達と映画を見ました。", exampleEn: "I watched a movie with a friend.", level: "N5" },
  { word: "家族", reading: "かぞく", romaji: "kazoku", meaning: "family", example: "家族と一緒にご飯を食べます。", exampleEn: "I eat with my family together.", level: "N5" },
  { word: "お父さん", reading: "おとうさん", romaji: "otōsan", meaning: "father", example: "お父さんは仕事をしています。", exampleEn: "Father is working.", level: "N5" },
  { word: "お母さん", reading: "おかあさん", romaji: "okāsan", meaning: "mother", example: "お母さんが料理を作ります。", exampleEn: "Mother makes meals.", level: "N5" },
  { word: "兄", reading: "あに", romaji: "ani", meaning: "older brother", example: "兄は大学に行っています。", exampleEn: "My older brother goes to university.", level: "N5" },
  { word: "姉", reading: "あね", romaji: "ane", meaning: "older sister", example: "姉は東京に住んでいます。", exampleEn: "My older sister lives in Tokyo.", level: "N5" },
  { word: "弟", reading: "おとうと", romaji: "otōto", meaning: "younger brother", example: "弟は学校が好きです。", exampleEn: "My younger brother likes school.", level: "N5" },
  { word: "妹", reading: "いもうと", romaji: "imōto", meaning: "younger sister", example: "妹は音楽が好きです。", exampleEn: "My younger sister likes music.", level: "N5" },
  { word: "先生", reading: "せんせい", romaji: "sensei", meaning: "teacher", example: "先生はとても親切です。", exampleEn: "The teacher is very kind.", level: "N5" },
  { word: "学生", reading: "がくせい", romaji: "gakusei", meaning: "student", example: "私は大学生です。", exampleEn: "I am a university student.", level: "N5" },

  // Core Nouns — Places
  { word: "家", reading: "いえ", romaji: "ie", meaning: "house / home", example: "家に帰ります。", exampleEn: "I return home.", level: "N5" },
  { word: "部屋", reading: "へや", romaji: "heya", meaning: "room", example: "部屋をきれいにします。", exampleEn: "I clean the room.", level: "N5" },
  { word: "学校", reading: "がっこう", romaji: "gakkō", meaning: "school", example: "学校は九時に始まります。", exampleEn: "School starts at nine.", level: "N5" },
  { word: "会社", reading: "かいしゃ", romaji: "kaisha", meaning: "company / office", example: "毎朝会社に行きます。", exampleEn: "I go to the office every morning.", level: "N5" },
  { word: "店", reading: "みせ", romaji: "mise", meaning: "shop / store", example: "あの店でパンを買います。", exampleEn: "I buy bread at that shop.", level: "N5" },
  { word: "駅", reading: "えき", romaji: "eki", meaning: "train station", example: "駅まで歩きます。", exampleEn: "I walk to the station.", level: "N5" },
  { word: "病院", reading: "びょういん", romaji: "byōin", meaning: "hospital", example: "病院に行かなければなりません。", exampleEn: "I have to go to the hospital.", level: "N5" },
  { word: "銀行", reading: "ぎんこう", romaji: "ginkō", meaning: "bank", example: "銀行でお金を引き出します。", exampleEn: "I withdraw money at the bank.", level: "N5" },
  { word: "公園", reading: "こうえん", romaji: "kōen", meaning: "park", example: "公園で散歩します。", exampleEn: "I take a walk in the park.", level: "N5" },
  { word: "レストラン", reading: "レストラン", romaji: "resutoran", meaning: "restaurant", example: "レストランで食べます。", exampleEn: "I eat at a restaurant.", level: "N5" },
  { word: "図書館", reading: "としょかん", romaji: "toshokan", meaning: "library", example: "図書館で本を読みます。", exampleEn: "I read books at the library.", level: "N5" },
  { word: "空港", reading: "くうこう", romaji: "kūkō", meaning: "airport", example: "空港まで電車で行きます。", exampleEn: "I go to the airport by train.", level: "N5" },
  { word: "郵便局", reading: "ゆうびんきょく", romaji: "yūbinkyoku", meaning: "post office", example: "郵便局で手紙を出します。", exampleEn: "I send a letter at the post office.", level: "N5" },

  // Core Nouns — Language & Communication
  { word: "言葉", reading: "ことば", romaji: "kotoba", meaning: "word / language", example: "難しい言葉が多いです。", exampleEn: "There are many difficult words.", level: "N5" },
  { word: "名前", reading: "なまえ", romaji: "namae", meaning: "name", example: "名前を教えてください。", exampleEn: "Please tell me your name.", level: "N5" },
  { word: "日本語", reading: "にほんご", romaji: "nihongo", meaning: "Japanese language", example: "日本語を勉強しています。", exampleEn: "I am studying Japanese.", level: "N5" },
  { word: "英語", reading: "えいご", romaji: "eigo", meaning: "English language", example: "英語が話せますか？", exampleEn: "Can you speak English?", level: "N5" },
  { word: "質問", reading: "しつもん", romaji: "shitsumon", meaning: "question", example: "質問があります。", exampleEn: "I have a question.", level: "N5" },
  { word: "答え", reading: "こたえ", romaji: "kotae", meaning: "answer", example: "答えが分かりません。", exampleEn: "I don't know the answer.", level: "N5" },

  // Core Nouns — Objects & Things
  { word: "本", reading: "ほん", romaji: "hon", meaning: "book", example: "毎日本を読みます。", exampleEn: "I read books every day.", level: "N5" },
  { word: "新聞", reading: "しんぶん", romaji: "shinbun", meaning: "newspaper", example: "朝に新聞を読みます。", exampleEn: "I read the newspaper in the morning.", level: "N5" },
  { word: "紙", reading: "かみ", romaji: "kami", meaning: "paper", example: "紙に書いてください。", exampleEn: "Please write on paper.", level: "N5" },
  { word: "鉛筆", reading: "えんぴつ", romaji: "enpitsu", meaning: "pencil", example: "鉛筆で書きます。", exampleEn: "I write with a pencil.", level: "N5" },
  { word: "電話", reading: "でんわ", romaji: "denwa", meaning: "telephone", example: "電話をかけます。", exampleEn: "I make a phone call.", level: "N5" },
  { word: "カメラ", reading: "カメラ", romaji: "kamera", meaning: "camera", example: "カメラで写真を撮ります。", exampleEn: "I take photos with a camera.", level: "N5" },
  { word: "車", reading: "くるま", romaji: "kuruma", meaning: "car", example: "車で会社に行きます。", exampleEn: "I go to work by car.", level: "N5" },
  { word: "自転車", reading: "じてんしゃ", romaji: "jitensha", meaning: "bicycle", example: "自転車で学校に行きます。", exampleEn: "I go to school by bicycle.", level: "N5" },
  { word: "電車", reading: "でんしゃ", romaji: "densha", meaning: "train", example: "毎日電車に乗ります。", exampleEn: "I ride the train every day.", level: "N5" },
  { word: "バス", reading: "バス", romaji: "basu", meaning: "bus", example: "バスで駅に行きます。", exampleEn: "I go to the station by bus.", level: "N5" },
  { word: "かばん", reading: "かばん", romaji: "kaban", meaning: "bag", example: "かばんに本を入れます。", exampleEn: "I put the book in the bag.", level: "N5" },
  { word: "服", reading: "ふく", romaji: "fuku", meaning: "clothes", example: "新しい服を買いました。", exampleEn: "I bought new clothes.", level: "N5" },
  { word: "靴", reading: "くつ", romaji: "kutsu", meaning: "shoes", example: "靴を脱いでください。", exampleEn: "Please take off your shoes.", level: "N5" },
  { word: "時計", reading: "とけい", romaji: "tokei", meaning: "watch / clock", example: "時計で時間を確認します。", exampleEn: "I check the time with a clock.", level: "N5" },
  { word: "鍵", reading: "かぎ", romaji: "kagi", meaning: "key", example: "鍵をなくしました。", exampleEn: "I lost my key.", level: "N5" },

  // Core Nouns — Food & Drink
  { word: "ご飯", reading: "ごはん", romaji: "gohan", meaning: "rice / meal", example: "ご飯を食べましょう。", exampleEn: "Let's eat a meal.", level: "N5" },
  { word: "水", reading: "みず", romaji: "mizu", meaning: "water", example: "水を一杯ください。", exampleEn: "Please give me a glass of water.", level: "N5" },
  { word: "お茶", reading: "おちゃ", romaji: "ocha", meaning: "tea", example: "お茶を飲みますか？", exampleEn: "Would you like some tea?", level: "N5" },
  { word: "コーヒー", reading: "コーヒー", romaji: "kōhī", meaning: "coffee", example: "毎朝コーヒーを飲みます。", exampleEn: "I drink coffee every morning.", level: "N5" },
  { word: "肉", reading: "にく", romaji: "niku", meaning: "meat", example: "肉が好きです。", exampleEn: "I like meat.", level: "N5" },
  { word: "魚", reading: "さかな", romaji: "sakana", meaning: "fish", example: "魚を料理します。", exampleEn: "I cook fish.", level: "N5" },
  { word: "野菜", reading: "やさい", romaji: "yasai", meaning: "vegetable", example: "野菜を毎日食べます。", exampleEn: "I eat vegetables every day.", level: "N5" },
  { word: "果物", reading: "くだもの", romaji: "kudamono", meaning: "fruit", example: "果物が好きです。", exampleEn: "I like fruit.", level: "N5" },
  { word: "パン", reading: "パン", romaji: "pan", meaning: "bread", example: "朝はパンを食べます。", exampleEn: "I eat bread in the morning.", level: "N5" },

  // Core Nouns — Nature & World
  { word: "国", reading: "くに", romaji: "kuni", meaning: "country", example: "どの国から来ましたか？", exampleEn: "Which country are you from?", level: "N5" },
  { word: "日本", reading: "にほん", romaji: "nihon", meaning: "Japan", example: "日本に住んでいます。", exampleEn: "I live in Japan.", level: "N5" },
  { word: "山", reading: "やま", romaji: "yama", meaning: "mountain", example: "山に登ります。", exampleEn: "I climb the mountain.", level: "N5" },
  { word: "川", reading: "かわ", romaji: "kawa", meaning: "river", example: "川の近くに家があります。", exampleEn: "My house is near the river.", level: "N5" },
  { word: "海", reading: "うみ", romaji: "umi", meaning: "sea / ocean", example: "夏に海に行きます。", exampleEn: "I go to the sea in summer.", level: "N5" },
  { word: "空", reading: "そら", romaji: "sora", meaning: "sky", example: "今日の空はきれいです。", exampleEn: "Today's sky is beautiful.", level: "N5" },
  { word: "天気", reading: "てんき", romaji: "tenki", meaning: "weather", example: "明日の天気はどうですか？", exampleEn: "How is the weather tomorrow?", level: "N5" },
  { word: "花", reading: "はな", romaji: "hana", meaning: "flower", example: "公園に花があります。", exampleEn: "There are flowers in the park.", level: "N5" },
  { word: "木", reading: "き", romaji: "ki", meaning: "tree", example: "大きい木の下にいます。", exampleEn: "I am under a big tree.", level: "N5" },
  { word: "犬", reading: "いぬ", romaji: "inu", meaning: "dog", example: "犬を飼っています。", exampleEn: "I have a dog.", level: "N5" },
  { word: "猫", reading: "ねこ", romaji: "neko", meaning: "cat", example: "猫が好きですか？", exampleEn: "Do you like cats?", level: "N5" },

  // Core Nouns — Abstract & Common
  { word: "お金", reading: "おかね", romaji: "okane", meaning: "money", example: "お金が足りません。", exampleEn: "I don't have enough money.", level: "N5" },
  { word: "仕事", reading: "しごと", romaji: "shigoto", meaning: "work / job", example: "仕事が忙しいです。", exampleEn: "Work is busy.", level: "N5" },
  { word: "勉強", reading: "べんきょう", romaji: "benkyō", meaning: "study", example: "毎日勉強します。", exampleEn: "I study every day.", level: "N5" },
  { word: "授業", reading: "じゅぎょう", romaji: "jugyō", meaning: "class / lesson", example: "授業は何時に始まりますか？", exampleEn: "What time does class start?", level: "N5" },
  { word: "宿題", reading: "しゅくだい", romaji: "shukudai", meaning: "homework", example: "宿題をしなければなりません。", exampleEn: "I have to do homework.", level: "N5" },
  { word: "試験", reading: "しけん", romaji: "shiken", meaning: "test / exam", example: "明日試験があります。", exampleEn: "There is an exam tomorrow.", level: "N5" },
  { word: "写真", reading: "しゃしん", romaji: "shashin", meaning: "photo / photograph", example: "写真を撮ってもいいですか？", exampleEn: "May I take a photo?", level: "N5" },
  { word: "音楽", reading: "おんがく", romaji: "ongaku", meaning: "music", example: "音楽を聴くのが好きです。", exampleEn: "I like listening to music.", level: "N5" },
  { word: "映画", reading: "えいが", romaji: "eiga", meaning: "movie", example: "映画を見に行きましょう。", exampleEn: "Let's go watch a movie.", level: "N5" },
  { word: "料理", reading: "りょうり", romaji: "ryōri", meaning: "cooking / dish", example: "日本料理が好きです。", exampleEn: "I like Japanese food.", level: "N5" },
  { word: "旅行", reading: "りょこう", romaji: "ryokō", meaning: "travel / trip", example: "来年旅行に行きます。", exampleEn: "I am going on a trip next year.", level: "N5" },
  { word: "道", reading: "みち", romaji: "michi", meaning: "road / way / path", example: "この道はどこへ行きますか？", exampleEn: "Where does this road go?", level: "N5" },
  { word: "地図", reading: "ちず", romaji: "chizu", meaning: "map", example: "地図を見てください。", exampleEn: "Please look at the map.", level: "N5" },

  // Additional Essential Verbs
  { word: "教える", reading: "おしえる", romaji: "oshieru", meaning: "to teach / tell", example: "日本語を教えてもらいました。", exampleEn: "I was taught Japanese.", level: "N5" },
  { word: "習う", reading: "ならう", romaji: "narau", meaning: "to learn", example: "ギターを習っています。", exampleEn: "I am learning guitar.", level: "N5" },
  { word: "遊ぶ", reading: "あそぶ", romaji: "asobu", meaning: "to play / hang out", example: "公園で遊びます。", exampleEn: "I play in the park.", level: "N5" },
  { word: "休む", reading: "やすむ", romaji: "yasumu", meaning: "to rest / take a break", example: "今日は家で休みます。", exampleEn: "I rest at home today.", level: "N5" },
  { word: "働く", reading: "はたらく", romaji: "hataraku", meaning: "to work", example: "毎日働きます。", exampleEn: "I work every day.", level: "N5" },
  { word: "洗う", reading: "あらう", romaji: "arau", meaning: "to wash", example: "手を洗ってください。", exampleEn: "Please wash your hands.", level: "N5" },
  { word: "着る", reading: "きる", romaji: "kiru", meaning: "to wear (clothing)", example: "コートを着ています。", exampleEn: "I am wearing a coat.", level: "N5" },
  { word: "脱ぐ", reading: "ぬぐ", romaji: "nugu", meaning: "to take off (clothing)", example: "靴を脱いでください。", exampleEn: "Please take off your shoes.", level: "N5" },
  { word: "開ける", reading: "あける", romaji: "akeru", meaning: "to open", example: "窓を開けてください。", exampleEn: "Please open the window.", level: "N5" },
  { word: "閉める", reading: "しめる", romaji: "shimeru", meaning: "to close / shut", example: "ドアを閉めてください。", exampleEn: "Please close the door.", level: "N5" },
  { word: "持つ", reading: "もつ", romaji: "motsu", meaning: "to hold / have", example: "かばんを持ちます。", exampleEn: "I carry a bag.", level: "N5" },
  { word: "置く", reading: "おく", romaji: "oku", meaning: "to put / place", example: "机の上に置いてください。", exampleEn: "Please put it on the desk.", level: "N5" },
  { word: "取る", reading: "とる", romaji: "toru", meaning: "to take / grab", example: "写真を取りました。", exampleEn: "I took a photo.", level: "N5" },
  { word: "貸す", reading: "かす", romaji: "kasu", meaning: "to lend", example: "本を貸してください。", exampleEn: "Please lend me the book.", level: "N5" },
  { word: "借りる", reading: "かりる", romaji: "kariru", meaning: "to borrow", example: "本を借りました。", exampleEn: "I borrowed a book.", level: "N5" },
  { word: "急ぐ", reading: "いそぐ", romaji: "isogu", meaning: "to hurry", example: "急いでください！", exampleEn: "Please hurry!", level: "N5" },
  { word: "困る", reading: "こまる", romaji: "komaru", meaning: "to be troubled / in trouble", example: "道が分からなくて困りました。", exampleEn: "I was troubled because I didn't know the way.", level: "N5" },

  // Location & Direction Words
  { word: "上", reading: "うえ", romaji: "ue", meaning: "above / on top", example: "机の上に本があります。", exampleEn: "There is a book on top of the desk.", level: "N5" },
  { word: "下", reading: "した", romaji: "shita", meaning: "below / under", example: "テーブルの下に猫がいます。", exampleEn: "There is a cat under the table.", level: "N5" },
  { word: "右", reading: "みぎ", romaji: "migi", meaning: "right (direction)", example: "右に曲がってください。", exampleEn: "Please turn right.", level: "N5" },
  { word: "左", reading: "ひだり", romaji: "hidari", meaning: "left (direction)", example: "左の建物が学校です。", exampleEn: "The building on the left is the school.", level: "N5" },
  { word: "前", reading: "まえ", romaji: "mae", meaning: "in front of / before", example: "駅の前に待っています。", exampleEn: "I am waiting in front of the station.", level: "N5" },
  { word: "後ろ", reading: "うしろ", romaji: "ushiro", meaning: "behind / back", example: "後ろを見てください。", exampleEn: "Please look behind you.", level: "N5" },
  { word: "中", reading: "なか", romaji: "naka", meaning: "inside / middle", example: "かばんの中に入れます。", exampleEn: "I put it inside the bag.", level: "N5" },
  { word: "外", reading: "そと", romaji: "soto", meaning: "outside", example: "外は寒いです。", exampleEn: "It is cold outside.", level: "N5" },
  { word: "近く", reading: "ちかく", romaji: "chikaku", meaning: "nearby / close", example: "駅の近くに住んでいます。", exampleEn: "I live near the station.", level: "N5" },
  { word: "遠い", reading: "とおい", romaji: "tōi", meaning: "far / distant", example: "学校は家から遠いです。", exampleEn: "The school is far from home.", level: "N5" },

  // Connectives & Structural Words
  { word: "そして", reading: "そして", romaji: "soshite", meaning: "and then / also", example: "ご飯を食べました。そして、映画を見ました。", exampleEn: "I ate a meal. And then I watched a movie.", level: "N5" },
  { word: "でも", reading: "でも", romaji: "demo", meaning: "but / however", example: "行きたい。でも、時間がありません。", exampleEn: "I want to go. But I don't have time.", level: "N5" },
  { word: "から", reading: "から", romaji: "kara", meaning: "because / from", example: "眠いから、早く寝ます。", exampleEn: "Because I'm sleepy, I go to bed early.", level: "N5" },
  { word: "だから", reading: "だから", romaji: "dakara", meaning: "therefore / so", example: "雨です。だから、家にいます。", exampleEn: "It's raining. So I am at home.", level: "N5" },
  { word: "また", reading: "また", romaji: "mata", meaning: "again / also", example: "またいつか会いましょう。", exampleEn: "Let's meet again someday.", level: "N5" },
  { word: "もう", reading: "もう", romaji: "mō", meaning: "already / not anymore", example: "もう食べました。", exampleEn: "I already ate.", level: "N5" },
  { word: "まだ", reading: "まだ", romaji: "mada", meaning: "still / not yet", example: "まだ食べていません。", exampleEn: "I haven't eaten yet.", level: "N5" },
  { word: "ちょっと", reading: "ちょっと", romaji: "chotto", meaning: "a little / just a moment", example: "ちょっと待ってください。", exampleEn: "Please wait a moment.", level: "N5" },
  { word: "とても", reading: "とても", romaji: "totemo", meaning: "very / extremely", example: "今日はとても寒いです。", exampleEn: "It is very cold today.", level: "N5" },
  { word: "本当に", reading: "ほんとうに", romaji: "hontō ni", meaning: "really / truly", example: "本当に美味しいです。", exampleEn: "It is really delicious.", level: "N5" },
  { word: "全然", reading: "ぜんぜん", romaji: "zenzen", meaning: "not at all / totally", example: "全然分かりません。", exampleEn: "I don't understand at all.", level: "N5" },
  { word: "あまり", reading: "あまり", romaji: "amari", meaning: "not very / not much", example: "あまり好きじゃないです。", exampleEn: "I don't like it very much.", level: "N5" },
  { word: "たくさん", reading: "たくさん", romaji: "takusan", meaning: "a lot / many", example: "たくさん食べました。", exampleEn: "I ate a lot.", level: "N5" },
  { word: "少し", reading: "すこし", romaji: "sukoshi", meaning: "a little / a bit", example: "少し待ってください。", exampleEn: "Please wait a bit.", level: "N5" },
  { word: "一緒に", reading: "いっしょに", romaji: "issho ni", meaning: "together", example: "一緒に行きましょう。", exampleEn: "Let's go together.", level: "N5" },
  { word: "だけ", reading: "だけ", romaji: "dake", meaning: "only / just", example: "一つだけください。", exampleEn: "Please give me just one.", level: "N5" },
  { word: "も", reading: "も", romaji: "mo", meaning: "also / too", example: "私も行きます。", exampleEn: "I will go too.", level: "N5" },
  { word: "毎日", reading: "まいにち", romaji: "mainichi", meaning: "every day", example: "毎日日本語を勉強します。", exampleEn: "I study Japanese every day.", level: "N5" },
  { word: "毎週", reading: "まいしゅう", romaji: "maishū", meaning: "every week", example: "毎週映画を見ます。", exampleEn: "I watch a movie every week.", level: "N5" },
  { word: "毎朝", reading: "まいあさ", romaji: "maiasa", meaning: "every morning", example: "毎朝走ります。", exampleEn: "I run every morning.", level: "N5" },

  // More Nouns
  { word: "場所", reading: "ばしょ", romaji: "basho", meaning: "place / location", example: "いい場所を知っています。", exampleEn: "I know a good place.", level: "N5" },
  { word: "声", reading: "こえ", romaji: "koe", meaning: "voice", example: "もっと大きい声で話してください。", exampleEn: "Please speak in a louder voice.", level: "N5" },
  { word: "目", reading: "め", romaji: "me", meaning: "eye", example: "目が痛いです。", exampleEn: "My eyes hurt.", level: "N5" },
  { word: "耳", reading: "みみ", romaji: "mimi", meaning: "ear", example: "耳が遠いです。", exampleEn: "I have poor hearing.", level: "N5" },
  { word: "手", reading: "て", romaji: "te", meaning: "hand", example: "手を洗ってください。", exampleEn: "Please wash your hands.", level: "N5" },
  { word: "足", reading: "あし", romaji: "ashi", meaning: "foot / leg", example: "足が痛いです。", exampleEn: "My foot hurts.", level: "N5" },
  { word: "頭", reading: "あたま", romaji: "atama", meaning: "head", example: "頭が痛いです。", exampleEn: "I have a headache.", level: "N5" },
  { word: "顔", reading: "かお", romaji: "kao", meaning: "face", example: "顔を洗います。", exampleEn: "I wash my face.", level: "N5" },
  { word: "体", reading: "からだ", romaji: "karada", meaning: "body", example: "体に気をつけてください。", exampleEn: "Please take care of your body.", level: "N5" },
  { word: "心", reading: "こころ", romaji: "kokoro", meaning: "heart / mind", example: "心から感謝します。", exampleEn: "I thank you from my heart.", level: "N5" },

  // ── N4 Core (301–500) ──

  // Essential N4 Verbs — Continuation & Change
  { word: "続ける", reading: "つづける", romaji: "tsuzukeru", meaning: "to continue", example: "毎日練習を続けます。", exampleEn: "I continue practicing every day.", level: "N4" },
  { word: "決める", reading: "きめる", romaji: "kimeru", meaning: "to decide", example: "どこへ行くか決めました。", exampleEn: "I decided where to go.", level: "N4" },
  { word: "始める", reading: "はじめる", romaji: "hajimeru", meaning: "to begin / start", example: "新しい仕事を始めます。", exampleEn: "I start a new job.", level: "N4" },
  { word: "終わる", reading: "おわる", romaji: "owaru", meaning: "to end / finish", example: "授業が終わりました。", exampleEn: "Class has finished.", level: "N4" },
  { word: "変わる", reading: "かわる", romaji: "kawaru", meaning: "to change", example: "計画が変わりました。", exampleEn: "The plan has changed.", level: "N4" },
  { word: "伝える", reading: "つたえる", romaji: "tsutaeru", meaning: "to convey / tell", example: "その話を友達に伝えます。", exampleEn: "I will convey that story to a friend.", level: "N4" },
  { word: "比べる", reading: "くらべる", romaji: "kuraberu", meaning: "to compare", example: "二つの値段を比べます。", exampleEn: "I compare the two prices.", level: "N4" },
  { word: "集める", reading: "あつめる", romaji: "atsumeru", meaning: "to collect / gather", example: "切手を集めています。", exampleEn: "I collect stamps.", level: "N4" },
  { word: "選ぶ", reading: "えらぶ", romaji: "erabu", meaning: "to choose / select", example: "好きなものを選んでください。", exampleEn: "Please choose what you like.", level: "N4" },
  { word: "覚える", reading: "おぼえる", romaji: "oboeru", meaning: "to remember / memorize", example: "新しい言葉を覚えます。", exampleEn: "I memorize new words.", level: "N4" },
  { word: "忘れる", reading: "わすれる", romaji: "wasureru", meaning: "to forget", example: "宿題を忘れました。", exampleEn: "I forgot my homework.", level: "N4" },
  { word: "諦める", reading: "あきらめる", romaji: "akirameru", meaning: "to give up", example: "諦めないでください。", exampleEn: "Please don't give up.", level: "N4" },
  { word: "頑張る", reading: "がんばる", romaji: "ganbaru", meaning: "to do one's best", example: "試験のために頑張ります。", exampleEn: "I will do my best for the exam.", level: "N4" },
  { word: "考える", reading: "かんがえる", romaji: "kangaeru", meaning: "to think / consider", example: "どうするか考えています。", exampleEn: "I am thinking about what to do.", level: "N4" },

  // N4 Emotion Verbs
  { word: "笑う", reading: "わらう", romaji: "warau", meaning: "to laugh / smile", example: "面白い話で笑いました。", exampleEn: "I laughed at the funny story.", level: "N4" },
  { word: "泣く", reading: "なく", romaji: "naku", meaning: "to cry", example: "映画を見て泣きました。", exampleEn: "I cried watching the movie.", level: "N4" },
  { word: "怒る", reading: "おこる", romaji: "okoru", meaning: "to get angry", example: "遅れたので怒られました。", exampleEn: "I was scolded because I was late.", level: "N4" },
  { word: "驚く", reading: "おどろく", romaji: "odoroku", meaning: "to be surprised", example: "そのニュースに驚きました。", exampleEn: "I was surprised by that news.", level: "N4" },

  // N4 Suru-Verbs
  { word: "心配する", reading: "しんぱいする", romaji: "shinpai suru", meaning: "to worry", example: "試験のことが心配です。", exampleEn: "I am worried about the exam.", level: "N4" },
  { word: "説明する", reading: "せつめいする", romaji: "setsumei suru", meaning: "to explain", example: "もう一度説明してください。", exampleEn: "Please explain it once more.", level: "N4" },
  { word: "練習する", reading: "れんしゅうする", romaji: "renshū suru", meaning: "to practice", example: "毎日ピアノを練習します。", exampleEn: "I practice piano every day.", level: "N4" },
  { word: "準備する", reading: "じゅんびする", romaji: "junbi suru", meaning: "to prepare", example: "旅行の準備をします。", exampleEn: "I prepare for the trip.", level: "N4" },
  { word: "相談する", reading: "そうだんする", romaji: "sōdan suru", meaning: "to consult / discuss", example: "先生に相談しました。", exampleEn: "I consulted with the teacher.", level: "N4" },
  { word: "連絡する", reading: "れんらくする", romaji: "renraku suru", meaning: "to contact / notify", example: "後で連絡します。", exampleEn: "I will contact you later.", level: "N4" },
  { word: "確認する", reading: "かくにんする", romaji: "kakunin suru", meaning: "to confirm / check", example: "予約を確認しました。", exampleEn: "I confirmed the reservation.", level: "N4" },
  { word: "利用する", reading: "りようする", romaji: "riyō suru", meaning: "to use / make use of", example: "アプリを利用します。", exampleEn: "I use the app.", level: "N4" },
  { word: "紹介する", reading: "しょうかいする", romaji: "shōkai suru", meaning: "to introduce", example: "友達を紹介します。", exampleEn: "I introduce my friend.", level: "N4" },
  { word: "注意する", reading: "ちゅういする", romaji: "chūi suru", meaning: "to be careful / pay attention", example: "車に注意してください。", exampleEn: "Please be careful of cars.", level: "N4" },

  // More N4 Verbs
  { word: "送る", reading: "おくる", romaji: "okuru", meaning: "to send", example: "メールを送ります。", exampleEn: "I send an email.", level: "N4" },
  { word: "受ける", reading: "うける", romaji: "ukeru", meaning: "to receive / take (an exam)", example: "試験を受けます。", exampleEn: "I take the exam.", level: "N4" },
  { word: "助ける", reading: "たすける", romaji: "tasukeru", meaning: "to help / rescue", example: "困った人を助けます。", exampleEn: "I help people in trouble.", level: "N4" },
  { word: "断る", reading: "ことわる", romaji: "kotowaru", meaning: "to refuse / decline", example: "お誘いを断りました。", exampleEn: "I declined the invitation.", level: "N4" },
  { word: "信じる", reading: "しんじる", romaji: "shinjiru", meaning: "to believe / trust", example: "あなたの言葉を信じます。", exampleEn: "I believe your words.", level: "N4" },
  { word: "楽しむ", reading: "たのしむ", romaji: "tanoshimu", meaning: "to enjoy", example: "旅行を楽しみます。", exampleEn: "I enjoy the trip.", level: "N4" },
  { word: "伝わる", reading: "つたわる", romaji: "tsutawaru", meaning: "to be conveyed / understood", example: "気持ちが伝わりましたか？", exampleEn: "Did my feelings get through?", level: "N4" },
  { word: "増える", reading: "ふえる", romaji: "fueru", meaning: "to increase", example: "友達が増えました。", exampleEn: "My friends have increased.", level: "N4" },
  { word: "減る", reading: "へる", romaji: "heru", meaning: "to decrease", example: "体重が減りました。", exampleEn: "My weight has decreased.", level: "N4" },
  { word: "直す", reading: "なおす", romaji: "naosu", meaning: "to fix / correct", example: "間違いを直します。", exampleEn: "I correct the mistake.", level: "N4" },
  { word: "調べる", reading: "しらべる", romaji: "shiraberu", meaning: "to investigate / look up", example: "インターネットで調べます。", exampleEn: "I look it up on the internet.", level: "N4" },
  { word: "気づく", reading: "きづく", romaji: "kizuku", meaning: "to notice / realize", example: "間違いに気づきました。", exampleEn: "I noticed the mistake.", level: "N4" },
  { word: "続く", reading: "つづく", romaji: "tsuzuku", meaning: "to continue (intransitive)", example: "雨が三日間続きました。", exampleEn: "The rain continued for three days.", level: "N4" },
  { word: "離れる", reading: "はなれる", romaji: "hanareru", meaning: "to leave / separate from", example: "故郷を離れました。", exampleEn: "I left my hometown.", level: "N4" },
  { word: "参加する", reading: "さんかする", romaji: "sanka suru", meaning: "to participate", example: "イベントに参加しました。", exampleEn: "I participated in the event.", level: "N4" },

  // N4 Adjectives — i-adjectives
  { word: "嬉しい", reading: "うれしい", romaji: "ureshii", meaning: "happy / glad", example: "プレゼントをもらって嬉しいです。", exampleEn: "I am happy to have received a present.", level: "N4" },
  { word: "悲しい", reading: "かなしい", romaji: "kanashii", meaning: "sad", example: "別れるのは悲しいです。", exampleEn: "It is sad to part ways.", level: "N4" },
  { word: "怖い", reading: "こわい", romaji: "kowai", meaning: "scary / afraid", example: "その映画はとても怖いです。", exampleEn: "That movie is very scary.", level: "N4" },
  { word: "恥ずかしい", reading: "はずかしい", romaji: "hazukashii", meaning: "embarrassed / shy", example: "人前で話すのが恥ずかしいです。", exampleEn: "I am embarrassed to speak in front of people.", level: "N4" },
  { word: "寂しい", reading: "さびしい", romaji: "sabishii", meaning: "lonely", example: "一人でいると寂しいです。", exampleEn: "I feel lonely when alone.", level: "N4" },
  { word: "痛い", reading: "いたい", romaji: "itai", meaning: "painful / ouch", example: "足が痛いです。", exampleEn: "My foot hurts.", level: "N4" },
  { word: "眠い", reading: "ねむい", romaji: "nemui", meaning: "sleepy", example: "昨日は眠くて授業中に寝てしまいました。", exampleEn: "I was so sleepy I fell asleep in class yesterday.", level: "N4" },
  { word: "珍しい", reading: "めずらしい", romaji: "mezurashii", meaning: "rare / unusual", example: "珍しい花を見ました。", exampleEn: "I saw a rare flower.", level: "N4" },
  { word: "正しい", reading: "ただしい", romaji: "tadashii", meaning: "correct / right", example: "この答えは正しいですか？", exampleEn: "Is this answer correct?", level: "N4" },

  // N4 Adjectives — na-adjectives & States
  { word: "疲れる", reading: "つかれる", romaji: "tsukareru", meaning: "to get tired", example: "今日はとても疲れました。", exampleEn: "I am very tired today.", level: "N4" },
  { word: "びっくり", reading: "びっくり", romaji: "bikkuri", meaning: "surprised / startled", example: "突然の電話にびっくりしました。", exampleEn: "I was startled by the sudden phone call.", level: "N4" },
  { word: "安心", reading: "あんしん", romaji: "anshin", meaning: "relief / peace of mind", example: "合格して安心しました。", exampleEn: "I felt relieved after passing.", level: "N4" },
  { word: "丁寧", reading: "ていねい", romaji: "teinei", meaning: "polite / careful", example: "丁寧に説明してくれました。", exampleEn: "They explained it to me politely.", level: "N4" },
  { word: "自由", reading: "じゆう", romaji: "jiyū", meaning: "free / freedom", example: "自由な時間が好きです。", exampleEn: "I like free time.", level: "N4" },
  { word: "複雑", reading: "ふくざつ", romaji: "fukuzatsu", meaning: "complicated", example: "この問題は複雑です。", exampleEn: "This problem is complicated.", level: "N4" },
  { word: "具体的", reading: "ぐたいてき", romaji: "gutaiteki", meaning: "concrete / specific", example: "具体的に説明してください。", exampleEn: "Please explain it specifically.", level: "N4" },
  { word: "必要", reading: "ひつよう", romaji: "hitsuyō", meaning: "necessary", example: "ビザが必要です。", exampleEn: "A visa is necessary.", level: "N4" },
  { word: "特別", reading: "とくべつ", romaji: "tokubetsu", meaning: "special", example: "今日は特別な日です。", exampleEn: "Today is a special day.", level: "N4" },
  { word: "普通", reading: "ふつう", romaji: "futsū", meaning: "ordinary / normal", example: "普通の日です。", exampleEn: "It is an ordinary day.", level: "N4" },
  { word: "急", reading: "きゅう", romaji: "kyū", meaning: "sudden / urgent", example: "急な用事ができました。", exampleEn: "An urgent matter came up.", level: "N4" },
  { word: "便利", reading: "べんり", romaji: "benri", meaning: "convenient", example: "スマホはとても便利です。", exampleEn: "Smartphones are very convenient.", level: "N4" },
  { word: "不便", reading: "ふべん", romaji: "fuben", meaning: "inconvenient", example: "交通が不便です。", exampleEn: "The transportation is inconvenient.", level: "N4" },

  // N4 Nouns — Emotions & States
  { word: "気持ち", reading: "きもち", romaji: "kimochi", meaning: "feeling / mood", example: "今日は気持ちがいいです。", exampleEn: "I feel good today.", level: "N4" },
  { word: "気分", reading: "きぶん", romaji: "kibun", meaning: "feeling / mood / atmosphere", example: "気分はどうですか？", exampleEn: "How are you feeling?", level: "N4" },
  { word: "感情", reading: "かんじょう", romaji: "kanjō", meaning: "emotion / feeling", example: "感情を表現することが大切です。", exampleEn: "It is important to express emotions.", level: "N4" },

  // N4 Nouns — Abstract Concepts
  { word: "意味", reading: "いみ", romaji: "imi", meaning: "meaning", example: "この言葉の意味は何ですか？", exampleEn: "What is the meaning of this word?", level: "N4" },
  { word: "理由", reading: "りゆう", romaji: "riyū", meaning: "reason", example: "なぜかの理由を教えてください。", exampleEn: "Please tell me the reason why.", level: "N4" },
  { word: "問題", reading: "もんだい", romaji: "mondai", meaning: "problem / issue", example: "大きい問題があります。", exampleEn: "There is a big problem.", level: "N4" },
  { word: "方法", reading: "ほうほう", romaji: "hōhō", meaning: "method / way", example: "いい方法を考えましょう。", exampleEn: "Let's think of a good method.", level: "N4" },
  { word: "関係", reading: "かんけい", romaji: "kankei", meaning: "relationship / connection", example: "二つの問題には関係があります。", exampleEn: "There is a connection between the two problems.", level: "N4" },
  { word: "機会", reading: "きかい", romaji: "kikai", meaning: "opportunity / chance", example: "いい機会だと思います。", exampleEn: "I think it is a good opportunity.", level: "N4" },
  { word: "目標", reading: "もくひょう", romaji: "mokuhyō", meaning: "goal / target", example: "今年の目標を決めました。", exampleEn: "I decided my goal for this year.", level: "N4" },
  { word: "夢", reading: "ゆめ", romaji: "yume", meaning: "dream", example: "将来の夢は何ですか？", exampleEn: "What is your dream for the future?", level: "N4" },
  { word: "将来", reading: "しょうらい", romaji: "shōrai", meaning: "future", example: "将来は医者になりたいです。", exampleEn: "In the future, I want to become a doctor.", level: "N4" },
  { word: "経験", reading: "けいけん", romaji: "keiken", meaning: "experience", example: "海外での経験は大切です。", exampleEn: "Overseas experience is important.", level: "N4" },
  { word: "習慣", reading: "しゅうかん", romaji: "shūkan", meaning: "habit / custom", example: "早起きは良い習慣です。", exampleEn: "Waking up early is a good habit.", level: "N4" },
  { word: "性格", reading: "せいかく", romaji: "seikaku", meaning: "personality / character", example: "彼女は明るい性格です。", exampleEn: "She has a cheerful personality.", level: "N4" },
  { word: "記念日", reading: "きねんび", romaji: "kinenbi", meaning: "anniversary / special day", example: "今日は結婚記念日です。", exampleEn: "Today is our wedding anniversary.", level: "N4" },

  // N4 Nouns — Society & Life
  { word: "生活", reading: "せいかつ", romaji: "seikatsu", meaning: "daily life / living", example: "日本での生活はどうですか？", exampleEn: "How is life in Japan?", level: "N4" },
  { word: "社会", reading: "しゃかい", romaji: "shakai", meaning: "society", example: "社会に貢献したいです。", exampleEn: "I want to contribute to society.", level: "N4" },
  { word: "文化", reading: "ぶんか", romaji: "bunka", meaning: "culture", example: "日本の文化が好きです。", exampleEn: "I like Japanese culture.", level: "N4" },
  { word: "意見", reading: "いけん", romaji: "iken", meaning: "opinion", example: "あなたの意見を聞かせてください。", exampleEn: "Please let me hear your opinion.", level: "N4" },
  { word: "情報", reading: "じょうほう", romaji: "jōhō", meaning: "information", example: "最新の情報が必要です。", exampleEn: "I need the latest information.", level: "N4" },
  { word: "計画", reading: "けいかく", romaji: "keikaku", meaning: "plan", example: "旅行の計画を立てました。", exampleEn: "I made a plan for the trip.", level: "N4" },
  { word: "予定", reading: "よてい", romaji: "yotei", meaning: "schedule / plan", example: "明日の予定を教えてください。", exampleEn: "Please tell me tomorrow's schedule.", level: "N4" },
  { word: "連絡", reading: "れんらく", romaji: "renraku", meaning: "contact / notification", example: "後で連絡してください。", exampleEn: "Please contact me later.", level: "N4" },
  { word: "結果", reading: "けっか", romaji: "kekka", meaning: "result / outcome", example: "試験の結果が出ました。", exampleEn: "The exam results came out.", level: "N4" },
  { word: "原因", reading: "げんいん", romaji: "gen'in", meaning: "cause / reason", example: "問題の原因は何ですか？", exampleEn: "What is the cause of the problem?", level: "N4" },
  { word: "場合", reading: "ばあい", romaji: "baai", meaning: "case / situation", example: "その場合はどうしますか？", exampleEn: "What will you do in that case?", level: "N4" },
  { word: "状況", reading: "じょうきょう", romaji: "jōkyō", meaning: "situation / circumstances", example: "状況を説明してください。", exampleEn: "Please explain the situation.", level: "N4" },

  // N4 Nouns — Practical
  { word: "予約", reading: "よやく", romaji: "yoyaku", meaning: "reservation / booking", example: "レストランの予約をしました。", exampleEn: "I made a restaurant reservation.", level: "N4" },
  { word: "申し込み", reading: "もうしこみ", romaji: "mōshikomi", meaning: "application / registration", example: "コースの申し込みをしました。", exampleEn: "I applied for the course.", level: "N4" },
  { word: "申込書", reading: "もうしこみしょ", romaji: "mōshikomisho", meaning: "application form", example: "申込書に記入してください。", exampleEn: "Please fill out the application form.", level: "N4" },
  { word: "交通", reading: "こうつう", romaji: "kōtsū", meaning: "transportation / traffic", example: "この町は交通が便利です。", exampleEn: "This town has convenient transportation.", level: "N4" },
  { word: "地域", reading: "ちいき", romaji: "chiiki", meaning: "area / region", example: "この地域は安全です。", exampleEn: "This area is safe.", level: "N4" },
  { word: "建物", reading: "たてもの", romaji: "tatemono", meaning: "building", example: "あの建物は有名です。", exampleEn: "That building is famous.", level: "N4" },
  { word: "玄関", reading: "げんかん", romaji: "genkan", meaning: "entrance / front door", example: "玄関で靴を脱ぎます。", exampleEn: "I take off my shoes at the entrance.", level: "N4" },
  { word: "窓", reading: "まど", romaji: "mado", meaning: "window", example: "窓を開けてもいいですか？", exampleEn: "May I open the window?", level: "N4" },

  // N4 Adverbs & Connectives
  { word: "しかし", reading: "しかし", romaji: "shikashi", meaning: "however / but", example: "行きたいです。しかし、お金がありません。", exampleEn: "I want to go. However, I don't have money.", level: "N4" },
  { word: "つまり", reading: "つまり", romaji: "tsumari", meaning: "in other words / that is", example: "つまり、行けないということですか？", exampleEn: "In other words, you can't go?", level: "N4" },
  { word: "例えば", reading: "たとえば", romaji: "tatoeba", meaning: "for example", example: "例えば、りんごやみかんが好きです。", exampleEn: "For example, I like apples and oranges.", level: "N4" },
  { word: "特に", reading: "とくに", romaji: "toku ni", meaning: "especially / particularly", example: "特に寿司が好きです。", exampleEn: "I especially like sushi.", level: "N4" },
  { word: "やはり", reading: "やはり", romaji: "yahari", meaning: "as expected / after all", example: "やはり日本語は難しいです。", exampleEn: "After all, Japanese is difficult.", level: "N4" },
  { word: "なかなか", reading: "なかなか", romaji: "nakanaka", meaning: "quite / fairly (with negative: not easily)", example: "なかなかうまくいきません。", exampleEn: "It does not go well easily.", level: "N4" },
  { word: "ぜひ", reading: "ぜひ", romaji: "zehi", meaning: "by all means / please do", example: "ぜひ遊びに来てください。", exampleEn: "Please come visit by all means.", level: "N4" },
  { word: "きっと", reading: "きっと", romaji: "kitto", meaning: "surely / certainly", example: "きっとうまくいきます。", exampleEn: "It will surely go well.", level: "N4" },
  { word: "もちろん", reading: "もちろん", romaji: "mochiron", meaning: "of course / certainly", example: "もちろん行きます。", exampleEn: "Of course I will go.", level: "N4" },
  { word: "急に", reading: "きゅうに", romaji: "kyū ni", meaning: "suddenly", example: "急に雨が降ってきました。", exampleEn: "It suddenly started to rain.", level: "N4" },
  { word: "だんだん", reading: "だんだん", romaji: "dandan", meaning: "gradually", example: "日本語がだんだん上手になってきました。", exampleEn: "My Japanese has gradually been getting better.", level: "N4" },
  { word: "ちゃんと", reading: "ちゃんと", romaji: "chanto", meaning: "properly / correctly", example: "ちゃんと勉強してください。", exampleEn: "Please study properly.", level: "N4" },

  // N4 Nouns — Broader Vocabulary
  { word: "お客さん", reading: "おきゃくさん", romaji: "okyakusan", meaning: "customer / guest", example: "お客さんがたくさん来ました。", exampleEn: "Many customers came.", level: "N4" },
  { word: "担当", reading: "たんとう", romaji: "tantō", meaning: "person in charge / responsible", example: "担当の方に聞いてください。", exampleEn: "Please ask the person in charge.", level: "N4" },
  { word: "代わり", reading: "かわり", romaji: "kawari", meaning: "substitute / replacement", example: "彼の代わりに来ました。", exampleEn: "I came in place of him.", level: "N4" },
  { word: "様子", reading: "ようす", romaji: "yōsu", meaning: "state / condition / appearance", example: "子供の様子を見てきます。", exampleEn: "I am going to check on the child.", level: "N4" },
  { word: "目的", reading: "もくてき", romaji: "mokuteki", meaning: "purpose / objective", example: "旅行の目的は何ですか？", exampleEn: "What is the purpose of your trip?", level: "N4" },
  { word: "内容", reading: "ないよう", romaji: "naiyō", meaning: "content / details", example: "手紙の内容を確認しました。", exampleEn: "I confirmed the contents of the letter.", level: "N4" },
  { word: "返事", reading: "へんじ", romaji: "henji", meaning: "reply / response", example: "返事をありがとうございます。", exampleEn: "Thank you for your reply.", level: "N4" },
  { word: "アドバイス", reading: "アドバイス", romaji: "adobaisu", meaning: "advice", example: "アドバイスをありがとうございます。", exampleEn: "Thank you for the advice.", level: "N4" },
  { word: "チャンス", reading: "チャンス", romaji: "chansu", meaning: "chance / opportunity", example: "いいチャンスを逃しました。", exampleEn: "I missed a good chance.", level: "N4" },
  { word: "ストレス", reading: "ストレス", romaji: "sutoresu", meaning: "stress", example: "ストレスが溜まっています。", exampleEn: "I have been accumulating stress.", level: "N4" },
  { word: "イメージ", reading: "イメージ", romaji: "imēji", meaning: "image / impression", example: "日本のイメージはどうですか？", exampleEn: "What is your image of Japan?", level: "N4" },

  // N4 — Health & Body
  { word: "健康", reading: "けんこう", romaji: "kenkō", meaning: "health", example: "健康のために運動します。", exampleEn: "I exercise for my health.", level: "N4" },
  { word: "病気", reading: "びょうき", romaji: "byōki", meaning: "illness / sickness", example: "病気になりました。", exampleEn: "I became sick.", level: "N4" },
  { word: "薬", reading: "くすり", romaji: "kusuri", meaning: "medicine / drug", example: "薬を飲んでください。", exampleEn: "Please take the medicine.", level: "N4" },
  { word: "医者", reading: "いしゃ", romaji: "isha", meaning: "doctor", example: "医者に行かなければなりません。", exampleEn: "I must go to the doctor.", level: "N4" },
  { word: "運動", reading: "うんどう", romaji: "undō", meaning: "exercise / sport", example: "毎日運動しています。", exampleEn: "I exercise every day.", level: "N4" },

  // N4 — Relationships & Communication
  { word: "相手", reading: "あいて", romaji: "aite", meaning: "partner / other person", example: "相手の気持ちを考えます。", exampleEn: "I think about the other person's feelings.", level: "N4" },
  { word: "お互い", reading: "おたがい", romaji: "otagai", meaning: "each other / mutual", example: "お互いに助け合いましょう。", exampleEn: "Let's help each other.", level: "N4" },
  { word: "態度", reading: "たいど", romaji: "taido", meaning: "attitude / manner", example: "彼の態度が気になります。", exampleEn: "His attitude bothers me.", level: "N4" },
  { word: "約束", reading: "やくそく", romaji: "yakusoku", meaning: "promise / appointment", example: "約束を守ります。", exampleEn: "I keep my promises.", level: "N4" },
  { word: "礼儀", reading: "れいぎ", romaji: "reigi", meaning: "manners / etiquette", example: "礼儀が大切です。", exampleEn: "Manners are important.", level: "N4" },

  // N4 — Work & Learning
  { word: "会議", reading: "かいぎ", romaji: "kaigi", meaning: "meeting", example: "会議に参加します。", exampleEn: "I participate in the meeting.", level: "N4" },
  { word: "報告", reading: "ほうこく", romaji: "hōkoku", meaning: "report", example: "結果を報告します。", exampleEn: "I report the results.", level: "N4" },
  { word: "資料", reading: "しりょう", romaji: "shiryō", meaning: "materials / documents", example: "資料を準備してください。", exampleEn: "Please prepare the materials.", level: "N4" },
  { word: "技術", reading: "ぎじゅつ", romaji: "gijutsu", meaning: "technology / skill", example: "技術を身につけたいです。", exampleEn: "I want to acquire a skill.", level: "N4" },
  { word: "能力", reading: "のうりょく", romaji: "nōryoku", meaning: "ability / capacity", example: "語学の能力を上げたいです。", exampleEn: "I want to improve my language ability.", level: "N4" },
  { word: "努力", reading: "どりょく", romaji: "doryoku", meaning: "effort", example: "努力すれば、できます。", exampleEn: "If you make an effort, you can do it.", level: "N4" },
  { word: "成功", reading: "せいこう", romaji: "seikō", meaning: "success", example: "プロジェクトが成功しました。", exampleEn: "The project was a success.", level: "N4" },
  { word: "失敗", reading: "しっぱい", romaji: "shippai", meaning: "failure / mistake", example: "失敗を恐れないでください。", exampleEn: "Please don't be afraid of failure.", level: "N4" },

  // Final N4 entries
  { word: "必ず", reading: "かならず", romaji: "kanarazu", meaning: "certainly / without fail", example: "必ず来てください。", exampleEn: "Please come without fail.", level: "N4" },
  { word: "最近", reading: "さいきん", romaji: "saikin", meaning: "recently / lately", example: "最近どうですか？", exampleEn: "How have you been lately?", level: "N4" },
  { word: "以前", reading: "いぜん", romaji: "izen", meaning: "before / previously", example: "以前会ったことがありますか？", exampleEn: "Have we met before?", level: "N4" },
  { word: "以後", reading: "いご", romaji: "igo", meaning: "from now on / after", example: "以後気をつけます。", exampleEn: "I will be careful from now on.", level: "N4" },
  { word: "ほとんど", reading: "ほとんど", romaji: "hotondo", meaning: "almost / mostly", example: "ほとんど終わりました。", exampleEn: "It is almost finished.", level: "N4" },
  { word: "お礼", reading: "おれい", romaji: "orei", meaning: "thanks / gratitude", example: "お礼を言いたいです。", exampleEn: "I want to express my thanks.", level: "N4" },
  { word: "素晴らしい", reading: "すばらしい", romaji: "subarashii", meaning: "wonderful / splendid", example: "素晴らしい景色ですね。", exampleEn: "What a wonderful view.", level: "N4" },
  { word: "ちょうど", reading: "ちょうど", romaji: "chōdo", meaning: "exactly / just right", example: "ちょうど三時です。", exampleEn: "It is exactly three o'clock.", level: "N4" },
  { word: "なるべく", reading: "なるべく", romaji: "narubeku", meaning: "as much as possible", example: "なるべく早く来てください。", exampleEn: "Please come as early as possible.", level: "N4" },

  // ── Additional N5 words (to reach 300) ──
  { word: "春", reading: "はる", romaji: "haru", meaning: "spring (season)", example: "春に花が咲きます。", exampleEn: "Flowers bloom in spring.", level: "N5" },
  { word: "夏", reading: "なつ", romaji: "natsu", meaning: "summer", example: "夏は暑いです。", exampleEn: "Summer is hot.", level: "N5" },
  { word: "秋", reading: "あき", romaji: "aki", meaning: "autumn / fall", example: "秋は葉がきれいです。", exampleEn: "The leaves are beautiful in autumn.", level: "N5" },
  { word: "冬", reading: "ふゆ", romaji: "fuyu", meaning: "winter", example: "冬はとても寒いです。", exampleEn: "Winter is very cold.", level: "N5" },
  { word: "雨", reading: "あめ", romaji: "ame", meaning: "rain", example: "今日は雨が降っています。", exampleEn: "It is raining today.", level: "N5" },
  { word: "雪", reading: "ゆき", romaji: "yuki", meaning: "snow", example: "外に雪が降っています。", exampleEn: "It is snowing outside.", level: "N5" },
  { word: "風", reading: "かぜ", romaji: "kaze", meaning: "wind", example: "今日は風が強いです。", exampleEn: "The wind is strong today.", level: "N5" },
  { word: "電気", reading: "でんき", romaji: "denki", meaning: "electricity / light", example: "電気を消してください。", exampleEn: "Please turn off the light.", level: "N5" },
  { word: "冷蔵庫", reading: "れいぞうこ", romaji: "reizōko", meaning: "refrigerator", example: "冷蔵庫に入れておきます。", exampleEn: "I will put it in the refrigerator.", level: "N5" },
  { word: "テレビ", reading: "テレビ", romaji: "terebi", meaning: "television", example: "テレビを見ます。", exampleEn: "I watch television.", level: "N5" },
  { word: "ドア", reading: "ドア", romaji: "doa", meaning: "door", example: "ドアを開けてください。", exampleEn: "Please open the door.", level: "N5" },
  { word: "トイレ", reading: "トイレ", romaji: "toire", meaning: "toilet / bathroom", example: "トイレはどこですか？", exampleEn: "Where is the bathroom?", level: "N5" },
  { word: "意地悪", reading: "いじわる", romaji: "ijiwaru", meaning: "mean / unkind", example: "意地悪なことを言わないでください。", exampleEn: "Please don't say mean things.", level: "N5" },
  { word: "電話番号", reading: "でんわばんごう", romaji: "denwa bangō", meaning: "phone number", example: "電話番号を教えてください。", exampleEn: "Please give me your phone number.", level: "N5" },
  { word: "大学", reading: "だいがく", romaji: "daigaku", meaning: "university", example: "大学で英語を勉強しています。", exampleEn: "I study English at university.", level: "N5" },

  // ── Additional N4 words (to reach 200) ──
  { word: "趣味", reading: "しゅみ", romaji: "shumi", meaning: "hobby / interest", example: "趣味は読書です。", exampleEn: "My hobby is reading.", level: "N4" },
  { word: "個性", reading: "こせい", romaji: "kosei", meaning: "individuality / character", example: "彼女は個性的な人です。", exampleEn: "She is a person with a unique character.", level: "N4" },
  { word: "印象", reading: "いんしょう", romaji: "inshō", meaning: "impression", example: "最初の印象は大切です。", exampleEn: "First impressions are important.", level: "N4" },
  { word: "雰囲気", reading: "ふんいき", romaji: "fun'iki", meaning: "atmosphere / vibe", example: "このカフェは雰囲気がいいです。", exampleEn: "This café has a good atmosphere.", level: "N4" },
  { word: "感謝", reading: "かんしゃ", romaji: "kansha", meaning: "gratitude / thanks", example: "感謝の気持ちを伝えます。", exampleEn: "I convey my feelings of gratitude.", level: "N4" },
  { word: "誤解", reading: "ごかい", romaji: "gokai", meaning: "misunderstanding", example: "誤解しないでください。", exampleEn: "Please don't misunderstand.", level: "N4" },
  { word: "確かに", reading: "たしかに", romaji: "tashika ni", meaning: "certainly / indeed", example: "確かにそうですね。", exampleEn: "That is certainly right.", level: "N4" },
  { word: "とにかく", reading: "とにかく", romaji: "tonikaku", meaning: "anyway / at any rate", example: "とにかくやってみます。", exampleEn: "Anyway, I will try it.", level: "N4" },
  { word: "さすが", reading: "さすが", romaji: "sasuga", meaning: "as expected / impressive", example: "さすがですね！", exampleEn: "As expected of you!", level: "N4" },
  { word: "せっかく", reading: "せっかく", romaji: "sekkaku", meaning: "with effort / specially", example: "せっかく来たのに、会えなかった。", exampleEn: "I came all this way but couldn't see them.", level: "N4" },
  { word: "今度", reading: "こんど", romaji: "kondo", meaning: "next time / this time", example: "今度一緒に行きましょう。", exampleEn: "Let's go together next time.", level: "N4" },
  { word: "普段", reading: "ふだん", romaji: "fudan", meaning: "usually / normally", example: "普段は何時に起きますか？", exampleEn: "What time do you usually wake up?", level: "N4" },
  { word: "どんな", reading: "どんな", romaji: "donna", meaning: "what kind of", example: "どんな音楽が好きですか？", exampleEn: "What kind of music do you like?", level: "N4" },
  { word: "そんな", reading: "そんな", romaji: "sonna", meaning: "such / that kind of", example: "そんなことを言わないでください。", exampleEn: "Please don't say such things.", level: "N4" },
  { word: "こんな", reading: "こんな", romaji: "konna", meaning: "this kind of", example: "こんな天気は嫌いです。", exampleEn: "I dislike this kind of weather.", level: "N4" },
  { word: "あんな", reading: "あんな", romaji: "anna", meaning: "that kind of (far)", example: "あんなに努力したのに。", exampleEn: "I worked that hard but still.", level: "N4" },
  { word: "同じ", reading: "おなじ", romaji: "onaji", meaning: "same", example: "同じ学校に通っています。", exampleEn: "We attend the same school.", level: "N4" },
  { word: "違う", reading: "ちがう", romaji: "chigau", meaning: "to differ / be wrong", example: "この答えは違います。", exampleEn: "This answer is wrong.", level: "N4" },
  { word: "気をつける", reading: "きをつける", romaji: "ki wo tsukeru", meaning: "to be careful", example: "道を渡る時は気をつけてください。", exampleEn: "Please be careful when crossing the road.", level: "N4" },
  { word: "楽になる", reading: "らくになる", romaji: "raku ni naru", meaning: "to become easier / feel better", example: "少し休んで楽になりました。", exampleEn: "I rested a bit and felt better.", level: "N4" },
  { word: "間に合う", reading: "まにあう", romaji: "ma ni au", meaning: "to be in time / make it", example: "電車に間に合いました。", exampleEn: "I made it in time for the train.", level: "N4" },
  { word: "落ち着く", reading: "おちつく", romaji: "ochitsuku", meaning: "to calm down / settle", example: "深呼吸して落ち着きました。", exampleEn: "I took a deep breath and calmed down.", level: "N4" },
  { word: "乗り換える", reading: "のりかえる", romaji: "norikaeru", meaning: "to transfer (train/bus)", example: "渋谷で電車を乗り換えます。", exampleEn: "I transfer trains at Shibuya.", level: "N4" },
  { word: "引っ越す", reading: "ひっこす", romaji: "hikkosu", meaning: "to move house", example: "来月新しい家に引っ越します。", exampleEn: "I move to a new house next month.", level: "N4" },
  { word: "片付ける", reading: "かたづける", romaji: "katazukeru", meaning: "to tidy up / put away", example: "部屋を片付けます。", exampleEn: "I tidy up the room.", level: "N4" },
  { word: "取り替える", reading: "とりかえる", romaji: "torikaeru", meaning: "to replace / exchange", example: "電池を取り替えます。", exampleEn: "I replace the battery.", level: "N4" },
  { word: "温める", reading: "あたためる", romaji: "atatameru", meaning: "to warm / heat up", example: "電子レンジで温めます。", exampleEn: "I warm it in the microwave.", level: "N4" },
  { word: "冷やす", reading: "ひやす", romaji: "hiyasu", meaning: "to cool / chill", example: "飲み物を冷蔵庫で冷やします。", exampleEn: "I chill the drink in the refrigerator.", level: "N4" },
  { word: "混む", reading: "こむ", romaji: "komu", meaning: "to be crowded", example: "朝の電車はとても混みます。", exampleEn: "Morning trains are very crowded.", level: "N4" },
  { word: "空く", reading: "すく", romaji: "suku", meaning: "to become empty / uncrowded", example: "午後になると電車が空きます。", exampleEn: "The train empties out in the afternoon.", level: "N4" },
  { word: "もし", reading: "もし", romaji: "moshi", meaning: "if / suppose", example: "もし時間があれば来てください。", exampleEn: "If you have time, please come.", level: "N4" },
  { word: "ため", reading: "ため", romaji: "tame", meaning: "for / because of", example: "健康のために運動します。", exampleEn: "I exercise for my health.", level: "N4" },
  { word: "ように", reading: "ように", romaji: "yō ni", meaning: "so that / in order to", example: "分かるように説明します。", exampleEn: "I explain so that you understand.", level: "N4" },
  { word: "ほど", reading: "ほど", romaji: "hodo", meaning: "to the extent / about", example: "一時間ほど待ちました。", exampleEn: "I waited for about one hour.", level: "N4" },
  { word: "によって", reading: "によって", romaji: "ni yotte", meaning: "by / depending on", example: "人によって意見が違います。", exampleEn: "Opinions differ depending on the person.", level: "N4" },
  { word: "に対して", reading: "にたいして", romaji: "ni taishite", meaning: "toward / regarding", example: "問題に対して考えます。", exampleEn: "I think about the problem.", level: "N4" },
  { word: "ながら", reading: "ながら", romaji: "nagara", meaning: "while doing", example: "音楽を聴きながら勉強します。", exampleEn: "I study while listening to music.", level: "N4" },
  { word: "てしまう", reading: "てしまう", romaji: "te shimau", meaning: "to end up doing / do completely", example: "宿題を忘れてしまいました。", exampleEn: "I ended up forgetting my homework.", level: "N4" },
  { word: "てみる", reading: "てみる", romaji: "te miru", meaning: "to try doing", example: "新しい料理を作ってみます。", exampleEn: "I will try making a new dish.", level: "N4" },
  { word: "ておく", reading: "ておく", romaji: "te oku", meaning: "to do in advance", example: "旅行の前に準備しておきます。", exampleEn: "I will prepare in advance before the trip.", level: "N4" },
  { word: "てある", reading: "てある", romaji: "te aru", meaning: "has been done (resultant state)", example: "もう予約してあります。", exampleEn: "I have already made a reservation.", level: "N4" },
  { word: "ていく", reading: "ていく", romaji: "te iku", meaning: "to continue doing / do and go", example: "これからも頑張っていきます。", exampleEn: "I will keep doing my best from now on.", level: "N4" },
  { word: "てくる", reading: "てくる", romaji: "te kuru", meaning: "to have been doing / do and come back", example: "買い物をしてきました。", exampleEn: "I went shopping and came back.", level: "N4" },
  { word: "お願い", reading: "おねがい", romaji: "onegai", meaning: "request / please", example: "お願いがあります。", exampleEn: "I have a request.", level: "N4" },
  { word: "残念", reading: "ざんねん", romaji: "zannen", meaning: "unfortunate / too bad", example: "残念ですが、行けません。", exampleEn: "Unfortunately, I cannot go.", level: "N4" },
  { word: "当然", reading: "とうぜん", romaji: "tōzen", meaning: "natural / of course", example: "それは当然のことです。", exampleEn: "That is a natural thing.", level: "N4" },
  { word: "様々", reading: "さまざま", romaji: "samazama", meaning: "various / diverse", example: "様々な意見があります。", exampleEn: "There are various opinions.", level: "N4" },
  { word: "以上", reading: "いじょう", romaji: "ijō", meaning: "more than / that's all", example: "三時間以上待ちました。", exampleEn: "I waited for more than three hours.", level: "N4" },
  { word: "以下", reading: "いか", romaji: "ika", meaning: "less than / below", example: "五点以下は不合格です。", exampleEn: "Below five points is a fail.", level: "N4" },
];

